version: "3.8"
services:
  db:
    image: mysql:8
    container_name: db
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
